#!/usr/bin/env python3
"""
update-workflows.py — Sync per-step subagent files for ALL workflows.

Scans .agent/workflows/templates/ recursively, calls init-workflow logic
for each workflow, and reports a global summary. Also performs a global
orphan scan: subagent files whose parent workflow has been entirely
deleted (not just a step renamed) are detected and removed here, since
init-workflow.py only knows about steps within one workflow it can find.

Usage:
    python .agent/scripts/update-workflows.py [--dry-run]

Exit codes:
    0 — success (sync complete or already up-to-date)
    1 — one or more workflows failed; see stderr
"""

import argparse
import glob as glob_module
import os
import sys


# Make init_workflow importable from the same scripts/ dir
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

GENERATED_MARKER = "# Auto-generated by init-workflow.py — DO NOT EDIT MANUALLY"
CLAUDE_AGENTS_DIR = os.path.join(".claude", "agents")


def _find_all_workflows():
    """Return list of workflow names by scanning templates/."""
    pattern = os.path.join(".agent", "workflows", "templates", "**", "workflow.yaml")
    paths = sorted(glob_module.glob(pattern, recursive=True))
    names = []
    for p in paths:
        # The directory name containing workflow.yaml is the workflow name
        names.append(os.path.basename(os.path.dirname(p)))
    return names, paths


def _find_global_orphans(known_workflow_names):
    """Find auto-generated subagent dirs whose parent workflow no longer exists.

    A subagent dir name has the form '<workflow>-<step>'. We split on hyphens
    and try every prefix length to find a workflow name match. If NO prefix
    matches a known workflow, the dir is a global orphan.
    """
    if not os.path.isdir(CLAUDE_AGENTS_DIR):
        return []

    known_set = set(known_workflow_names)
    orphans = []
    for entry in sorted(os.listdir(CLAUDE_AGENTS_DIR)):
        full_path = os.path.join(CLAUDE_AGENTS_DIR, entry)
        if not os.path.isdir(full_path):
            continue
        agent_md = os.path.join(full_path, "AGENT.md")
        if not os.path.isfile(agent_md):
            continue
        # Only delete files we generated ourselves
        try:
            with open(agent_md, "r", encoding="utf-8") as f:
                content = f.read()
        except OSError:
            continue
        if GENERATED_MARKER not in content:
            continue
        # Try to match against any known workflow name (longest prefix wins).
        # Subagent dirs are named '<workflow>-<step>' so we split on hyphens
        # and reconstruct possible workflow names from leftmost portions.
        parts = entry.split("-")
        matched = False
        for split_at in range(len(parts) - 1, 0, -1):
            candidate_wf = "-".join(parts[:split_at])
            if candidate_wf in known_set:
                matched = True
                break
        if not matched:
            orphans.append(entry)
    return orphans


def _delete_global_orphan(name, dry_run=False):
    full_path = os.path.join(CLAUDE_AGENTS_DIR, name)
    agent_md = os.path.join(full_path, "AGENT.md")
    if dry_run:
        return
    try:
        if os.path.isfile(agent_md):
            os.remove(agent_md)
        os.rmdir(full_path)
    except OSError as e:
        sys.stderr.write(f"Failed to delete {full_path}: {e}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Sync per-step subagent files for all workflows."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without writing files",
    )
    args = parser.parse_args()

    # Import init-workflow.py module by file path (it has a hyphen in name)
    import importlib.util
    init_path = os.path.join(SCRIPT_DIR, "init-workflow.py")
    if not os.path.isfile(init_path):
        sys.stderr.write(f"ERROR: init-workflow.py not found at {init_path}\n")
        sys.exit(1)
    spec = importlib.util.spec_from_file_location("init_workflow", init_path)
    init_workflow_mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(init_workflow_mod)

    names, paths = _find_all_workflows()
    if not names:
        print("No workflows found in .agent/workflows/templates/")
        return

    print(f"Found {len(names)} workflow(s) to sync")
    print()

    totals = {"created": 0, "updated": 0, "unchanged": 0, "deleted": 0}
    failed = []
    any_changes = False

    for name in names:
        try:
            result = init_workflow_mod.init_workflow(name, dry_run=args.dry_run)
            for k in totals:
                totals[k] += len(result.get(k, []))
            if result.get("total", 0) > 0:
                any_changes = True
        except SystemExit as e:
            failed.append((name, f"exit {e.code}"))
        except Exception as e:
            failed.append((name, str(e)))
        print()

    # Global orphan scan: subagent dirs whose parent workflow is gone.
    # init-workflow.py only handles orphans within ONE workflow (steps
    # removed from a workflow that still exists). This catches the case
    # where the entire workflow.yaml has been deleted.
    global_orphans = _find_global_orphans(names)
    if global_orphans:
        print()
        print("Global orphan cleanup (workflows fully removed):")
        for orphan in global_orphans:
            _delete_global_orphan(orphan, dry_run=args.dry_run)
            totals["deleted"] += 1
            any_changes = True
            print(f"  DELETED  {orphan} (orphan — workflow no longer exists)")

    print()
    print("=" * 60)
    print(f"Global summary: {totals['created']} created, "
          f"{totals['updated']} updated, "
          f"{totals['unchanged']} unchanged, "
          f"{totals['deleted']} deleted")

    if failed:
        print()
        print(f"FAILED workflows ({len(failed)}):")
        for name, err in failed:
            print(f"  - {name}: {err}")

    if any_changes:
        print()
        print("[!] Restart Claude Code to load the new/updated subagents.")

    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
